image: node:latest

stages:
  - lint
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn

before_script:
  - yarn config set cache-folder .yarn
  - yarn install

lint:
  stage: lint
  script:
    - yarn lint

test:
  stage: test
  script:
    - yarn test

build:
  stage: build
  script:
    - yarn build
